name: build_ErfanGSIs

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  push:
    branches:
      - main
      - master
  watch:
    types: [started]
    
env:
  ROM_URL: https://9b56tf8qppton1i352b7u6g21nm2k4drh25pv5l5fe0b9ir8hc6fv339.qc.dolfincdnx.net:7843/xdispatch717658027700532a/bigota.d.miui.com/V14.0.1.0.SJNCNXM/miui_CEZANNE_V14.0.1.0.SJNCNXM_cbba55822d_12.0.zip?BSLuBan=eyJob3N0IjoiYmlnb3RhLmQubWl1aS5jb20iLCJic3JlcWlkIjoiYTRiZmFjYWFiMDdjNTRlMzliZjBiYWU3ZmZiZGZmMDkiLCJjYWNoZV9rZXkiOiJcL1YxNC4wLjEuMC5TSk5DTlhNXC9taXVpX0NFWkFOTkVfVjE0LjAuMS4wLlNKTkNOWE1fY2JiYTU1ODIyZF8xMi4wLnppcCIsImRuc19ob3N0IjoicGYwMDMudi5ic2dzbGIuY24iLCJrZXkiOiJlNzVjZGRjODE4OWIzY2Y1NzBjMTllYTMxMDcyZDc0ZCIsInRzIjoxNjgyNzQ0OTU2fQ==
  ROM_NAME: k30u
  BUILD_TYPE: ab
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initialization environment
         run: |
            sudo -E apt-get -qq install git wget
       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs.git ErfanGSIs
         
       - name: Fix exit
         run: |
              sed -i 's/\|\| exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
              sed -i 's/exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
       
       - name: Setting up ErfanGSI requirements
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs
              mkdir ./output
              sudo bash ./setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: |
              cd  $GITHUB_WORKSPACE/ErfanGSIs
              sudo bash ./url2GSI.sh -c --$BUILD_TYPE $ROM_URL $ROM_NAME
       
       - name: Zip GSI  
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs/output
              mkdir final
              zip -r final/GSI.zip ./*
       
       - name: Upload GSI to WeTransfer
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs/output
              curl -sL https://git.io/file-transfer | sh
              ./transfer wet ./final/GSI.zip

         
            
